pypa/installer

- .github/workflows/ci.yml
From `ci: cache nox`
> Right now, we recreate the nox environment on every CI run, which is wasteful
> as it can take a while to to create it.
>
> This patch caches the nox environment so that it doesn't need to be
> recreated on every CI run. The cache will only be updated once a day.
>
> If at some point we save a bad environment or the cached environment
> becomes incompatible with newer nox versions, we should bump the
> version (currently v1) in the cache key, to force the cache to be
> recreated.
>
> Signed-off-by: Filipe Laíns <lains@archlinux.org>
> Cache nox & pip in CI

- .flake8
- src/installer/records.py
- tests/test_records.py
I opted for `validate` to receive `bytes` as this should be compatible with both `ZipFile` and normal files, but this *could* be a problem with big files. What do you think?
If we choose to receive a `BinaryIO` instead of `bytes` it could be tricky to get the size. I guess if the object is seekable, we can seek to the end and use `tell`.
> records: add RecordItem.validate()

- src/installer/records.py
Context: https://github.com/pradyunsg/installer/pull/16#discussion_r443342513
> Stop using os.linesep when reading RECORD with `csv`

- src/installer/destinations.py
- src/installer/sources.py
- tests/test_destinations.py
- tests/test_sources.py
A couple of rough design notes:
- The `WheelSource` is intentionally not tied to any properties within this package -- this allows other projects (such as `wheel`) to implement this interface without needing to add a dependency.
- The `WheelDestination` is where nearly all of the logical "nuance" of script generation and RECORD writing lives. This is an intentional choice. This allows for the "core" to only need to know how the wheel file is structured, and correctly invoke this class.
This is NOT "the final API" -- the plan/expectation is that there would likely be more iterations on this as we get feedback on how this works when trying implementing this interface; as the "core" is implemented and as the concrete implementations for these are written. And, yes, there's also gonna be …
> Add initial "source" and "destination" abstractions

- docs/api/records.md
- src/installer/destinations.py
- src/installer/records.py
- src/installer/sources.py
- tests/test_records.py
The Record class only represents on record entry in the RECORD file,
RecordEntry makes that a bit more clear.
Signed-off-by: Filipe Laíns <lains@riseup.net>
> record: rename Record to RecordEntry

- docs/index.md
Use a script that has been tested locally, to make sure that it works.
> Fix documentation's opening example

- src/installer/_core.py
- src/installer/destinations.py
- src/installer/utils.py
- tests/test_core.py
- tests/test_utils.py
I am currently trying to integrate `installer` into Poetry and things are mostly good but there were issues with how the entrypoints were managed. More specifically:
- The entry points file was not properly detected (`installer` was looking for a `entry-points.txt` file while the actual file is `entry_points.txt`).
- Assertion errors were raised for some entry points (either because they did not match the regexp or were missing the attribute part, which is not required for non-script entry points). This was fixed by ensuring that the `parse_entrypoints()` function only parses script entry points.
- Finally, generated scripts were not executable.
> Fix entrypoints management

- .github/workflows/ci.yml
- src/installer/records.py
I noticed on #94 that most of the CI jobs were not actually running the tests! Only the PyPy job was actually running the tests.
It appears that specifying `-s <session1> -s <session2>` for nox doesn't work - only the last session specified runs. It needs to be specified like `-s <session1> <session2>` instead.
> Run tests on CPython on Github actions

- src/installer/_core.py
- src/installer/destinations.py
- src/installer/sources.py
- src/installer/utils.py
- tests/test_core.py
- tests/test_destinations.py
- tests/test_sources.py
This is a property of individual files in the wheel, and thus needs to be parsed
by the `WheelSource`, and needs special handling in `WheelDestination`. It also
needs to be propagated through the entire pipeline, since the information needs
to be exchanged between the two components.
Closes #68
> Preserve the executable bit from wheel contents

- pyproject.toml
- src/installer/__main__.py
- src/installer/destinations.py
- tests/conftest.py
- tests/test_main.py
- tests/test_sources.py
This starts from #66, and moves the added functionality for destdir & bytecode compilation into the Python API (`SchemeDictionaryDestination`), so the CLI is a thinner wrapper over the Python API. It also drops the compatibility checks, so `installer` once again has no dependencies.
Alternative to #92, for consideration.
Closes #93
> CLI to install to Python running installer

- src/installer/sources.py
These are incompatible with import-rewriting mechanisms for vendoring
existing code.
> Move away from `import installer.xyz` style imports

- src/installer/records.py
- src/installer/utils.py
- tests/test_destinations.py
- tests/test_records.py
To correctly quote paths in the record entry.
Fix #117
> Construct RECORD file using csv.writer

- src/installer/__main__.py
- tests/test_main.py
Implement a --prefix option that can be used to override platbase
and base when expanding the paths from install scheme.  This can be used
to install paths to a layout using another prefix than the one used
to run installer.
Gentoo use case for this is running installer inside a venv to prepare
installation images for the real system.  The nixOS maintainers have
also indicated interest in this feature.
Fixes #98
> Implement `--prefix` option

- src/installer/utils.py
- tests/test_destinations.py
- tests/test_utils.py
Installer was generating `dist-info` `RECORD` files with invalid hashes. Specifically, it was encoding the hashes in hexadecimal, but [PEP 376][] specifies that they are to be encoded in urlsafe-base64-nopad. Bizarrely, Installer's own `records.Hash` class implements a `validate` method that checks a recorded hash against the *correctly* encoded hash of the corresponding file, meaning that Installer could never validate the very records that it itself had generated.
Fix the `utils.copyfileobj_with_hashing` function so that it returns correctly encoded hashes, and fix up `TestCopyFileObjWithHashing` and `TestSchemeDictionaryDestination` to check that the hashes are encoded as specified by [PEP 376][].
[PEP 376]: https://peps.python.org/pep-0376/
> Encode hashes in RECORD files correctly according to PEP 376

- .github/workflows/ci.yml
- noxfile.py
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)
> Add support for Python 3.11

- src/installer/sources.py
- src/installer/utils.py
- tests/test_sources.py
- tests/test_utils.py
Some wheels don't use normalized names for their `.dist-info` directories, so search the wheel for them.
Fixes: #134
> Search wheels for `.dist-info` directories

- src/installer/utils.py
The documentation in
https://packaging.python.org/en/latest/specifications/core-metadata/ claims that metadata should be parsed with compat32 policy.
The documentation in
https://docs.python.org/3/library/email.parser.html#feedparser-api claims that policy should always be specified and that the default will change at some point. When CPython changes the default, that would presumably introduce a bug here.
> Explicitly use policy=compat32

- src/installer/sources.py
- tests/test_sources.py
> Refactor `validate_record`

- src/installer/__main__.py
- tests/test_main.py
Corresponding to #147.
`python -m installer --validate-record=all pkg.whl`
Choices are `all` `entries` (only name precedence in RECORD) and `none` (default)
> Add `--validate-record` to CLI

- src/installer/__main__.py
a kwarg was left off of the call in #161
> Pass kwarg for `validate_record` when called from CLI

- src/installer/scripts.py
- tests/test_scripts.py
Signed-off-by: Frost Ming <me@frostming.com>
Resolve #180
> Use pythonw.exe instead of python.exe for GUI scripts on Windows

- src/installer/records.py
- src/installer/sources.py
- src/installer/utils.py
- tests/test_records.py
- tests/test_utils.py
Supercedes and closes #183 
Fixes #185 
This ensures that the validation can be performed without loading the entire file in-memory.
> Validate RECORD file using streams instead of reading in-memory

- CONTRIBUTING.md
- docs/development/workflow.md
- docs/index.md
- src/installer/scripts.py
The docs link took me to the wrong source repo
> move links from fork to pypa

- .pre-commit-config.yaml
The mirror uses a mypyc-compiled wheel which is faster.
https://github.com/psf/black-pre-commit-mirror
Also update some pins whilst we're here.
> Use Black mirror for faster pre-commit

- src/installer/scripts.py
**B904** Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
> Apply flake8-bugbear rule

- docs/cli/installer.md
- src/installer/__main__.py
- tests/conftest.py
- tests/test_main.py
Allow specifying multiple `wheel` arguments to the installer CLI.
> Add CLI support for installing multiple wheels

- src/installer/records.py
- src/installer/scripts.py
```
UP032 Use f-string instead of `format` call
```
https://docs.astral.sh/ruff/rules/f-string/
> Apply ruff/pyupgrade rule (UP032)

- CONTRIBUTING.md
- src/installer/destinations.py
```
…\hatch on  workspaces [!] via  v3.11.7
❯ python -m timeit -n 1 -r 1 "import installer"
1 loop, best of 1: 71.6 msec per loop
…\hatch on  workspaces [!] via  v3.11.7
❯ python -m timeit -n 1 -r 1 "import compileall"
1 loop, best of 1: 14.4 msec per loop
```
> Lazily import compileall

- pyproject.toml
See:
https://learn.scientific-python.org/development/guides/repo-review/?repo=pypa%2Finstaller&branch=main
> MY102: MyPy show_error_codes deprecated
> 
> Must not have `show_error_codes`. It is now the default, or you can use `hide_error_codes` with the reverse value instead (since MyPy v0.990).
> Apply repo-review rule MY102

- .pre-commit-config.yaml
Since version 2.0, `pyproject-fmt` introduced a very opinionated format of the `pyproject.toml` file, which (in this maintainer's opinion) obfuscates the readability of the file in question. For that reason, I think deleting it is the best option (since `pre-commit` doesn't allow pinning hooks to a specific version and manually correcting it in the autoupdates is cumbersome).
> Remove pyproject-fmt

- src/installer/__main__.py
- src/installer/destinations.py
- tests/test_destinations.py
Took a stab at implementing what I suggested in #215.
Implement the `--force` option that, if supplied, will make installer overwrite any already existing package files instead of failing. With this flag, installer can be used in an idempotent manner, i.e. the same command can be executed multiple times with the same result:
```sh
python -m installer --force --destdir=tmp dist/*.whl
python -m installer --force --destdir=tmp dist/*.whl
python -m installer --force --destdir=tmp dist/*.whl
```
One other candidate for the option name I have in mind is  `--overwrite` which I think is more mechanically descriptive, but it might be less ubiquitous, as tools like `mv` and `cp` use `-f/--force`.
Resolves #215
> Add --overwrite-existing option that overwrites existing files

- src/installer/destinations.py
- src/installer/records.py
- src/installer/scripts.py
Python 3.7 has been the minimum requirement for a while now, which brings dataclasses into the standard library. This reduces the boilerplate necessary to write nice classes with init and repr methods that simply do the right thing.
As a side effect, fix the repr of installer.scripts.Script, which was missing the trailing close-parenthesis:
```
>>> import installer
>>> installer.scripts.Script('name', 'module', 'attr', 'section')
Script(name='name', module='module', attr='attr'
```
> Migrate several classes over to dataclasses

- .pre-commit-config.yaml
- pyproject.toml
https://learn.scientific-python.org/development/guides/repo-review/?repo=pypa%2Finstaller&branch=main
Rules [`RF101`](https://learn.scientific-python.org/development/guides/style#RF101) and [`RF103`](https://learn.scientific-python.org/development/guides/style#RF103)will be enforced by #230.
> Apply repo-review rules

- src/installer/utils.py
- tests/test_destinations.py
This helps build reproducibility by ensuring the RECORD file is the same regardless of the order of the input files.
> src/installer/utils.py: sort entries before writing out RECORD file

- src/installer/scripts.py
Python 3.13 decided to keep the old `importlib.resources` APIs, so the conditional import is no longer necessary. I also decided to pull private functions into the `Script` class, since those were not used anywhere outside of it.
> Small refactor to `installer.scripts`

- src/installer/__main__.py
- tests/test_main.py
> Implement `--executable' option (#257)
