pypa/installer

- src/installer/_compat/pathlib.py
- src/installer/_compat/typing.py
- src/installer/records.py
As discussed in https://github.com/pradyunsg/installer/pull/3#discussion_r418959810
> Move __all__ after import statements

- src/installer/records.py
- tests/test_records.py
Follow up on #2, builds upon #11
> Rework installer.records

- src/installer/records.py
Signed-off-by: Filipe Laíns <lains@archlinux.org>
> records: add Hash.validate()

- .pre-commit-config.yaml
- .pydocstyle
- docs/_static/custom.css
- docs/api/index.rst
- docs/api/records.rst
- docs/api/scripts.rst
- docs/conf.py
- docs/index.rst
- docs/navigation.html
- noxfile.py
- src/installer/__init__.py
- src/installer/_compat/__init__.py
- src/installer/_compat/importlib_resources.py
- src/installer/_compat/typing.py
- src/installer/_scripts/__init__.py
- src/installer/records.py
- src/installer/scripts.py
> Document all the existing components + proper Sphinx documentation

- src/installer/records.py
- tests/test_records.py
* Add `__str__` to `installer.records.Record` and `installer.records.Hash`.
* Add tests for the string representation
> Add a string representation to `Record`

- .pre-commit-config.yaml
- docs/conf.py
- mypy.ini
- src/installer/_compat/typing.py
- src/installer/records.py
- src/installer/scripts.py
- tests/test_basic.py
- tests/test_records.py
Miscellaneous changes that don't quite fit in with any of my other changes. :)
> Generic cleanups

- docs/api/utils.md
- src/installer/_compat/typing.py
- src/installer/utils.py
- tests/test_utils.py
> Implement the parsing utilities for end users

- src/installer/destinations.py
- tests/test_destinations.py
Shoutout to @FFY00, coz I hadn't thought thoroughly about this. :)
> Add WheelDestination.write_script

- src/installer/utils.py
- tests/test_utils.py
Co-authored-by: Laszlo Kiss-Kollar <kiss.kollar.laszlo@gmail.com>
This is primarily helper for implementing `WheelDestination.write_file`.
> Add `copyfileobj_with_hashing`

- src/installer/destinations.py
- tests/test_destinations.py
Because, @FFY00 figured out that we're gonna need this to write the RECORD. :)
> Add record_file_path to WheelDestination.finalize_installation

- src/installer/_compat/__init__.py
- src/installer/destinations.py
- src/installer/scripts.py
- src/installer/utils.py
- tests/test_destinations.py
- tests/test_utils.py
Signed-off-by: Filipe Laíns <lains@riseup.net>
> Add initial implementation of `SchemeDictionaryDestination`

- src/installer/destinations.py
- src/installer/utils.py
Fixes #49
Signed-off-by: Filipe Laíns <lains@riseup.net>
>  destinations: SchemeDictionaryDestination._write_file to write_to_fs 

- .github/workflows/ci.yml
Follows what was done to address pypa/setuptools#3093
> Add concurrency limit in CI

- src/installer/_core.py
- tests/test_core.py
The `is_executable` is from the last for-loop and is unbound in adding `additional_metadata`. Fix it to `False` as additional metadata are likely not executable.
> Fix the unbound is_executable

- src/installer/records.py
- tests/test_records.py
> Normalize RECORD file paths when parsing

- src/installer/sources.py
- tests/test_sources.py
> Improve handling of non-normalized `.dist-info` folders

- .pre-commit-config.yaml
- pyproject.toml
- src/installer/records.py
- src/installer/sources.py
- src/installer/utils.py
- tools/update_launchers.py
complete the typechecking, tighten up mypy configuration
> Complete type annotations and strictify mypy

- noxfile.py
- src/installer/utils.py
- tests/test_utils.py
An assortment of minor cleanups that I don't think need to be separate PRs.
> Cleanup certain rough edges

- .pre-commit-config.yaml
- pyproject.toml
Extracted from https://github.com/pypa/installer/pull/201 to make a cleaner diff there.
References:
* https://pyproject-fmt.readthedocs.io/en/latest/
> Auto-format `pyproject.toml` with `pyproject-fmt` tool

- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
- src/installer/__main__.py
- src/installer/_core.py
- src/installer/destinations.py
- src/installer/records.py
- src/installer/scripts.py
- src/installer/sources.py
- src/installer/utils.py
- tests/test_sources.py
Drop support for Python 3.8 and add a classifier for Python 3.13
> Drop support for Python 3.8

- src/installer/__main__.py
- tests/test_main.py
This reverts commit 375cd94ecb2455f1c459b333c8c871ba6ef81754.
> Revert "Implement `--executable' option (#257) (#258)"

- pyproject.toml
> Rename ruff ruleset: `TCH` → `TC`

- pyproject.toml
- tests/test_sources.py
See https://github.com/pypa/installer/pull/277#discussion_r2072631625.
> Enforce ruff/flynt rules (FLY)
